pipeline { 
    agent any

    tools{
        maven 'maven 3.9.9'
    }

    stages{ 
        stage('build'){ 
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'running unit tests on worker app'
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app into a jarfile'
            } 
        } 
    }
    post{ 
        always{ 
            echo 'the job is complete' 

    }
  }
}
